courseapp-mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=coursedb
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbp4ss

courseApp:
  image: courseapp
  links:
    - courseapp-mysql:mysql:latest
  ports:
    - 8080:8080
